# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - gzip -kfn9 packaging/srs-milter.1
builds:
  -
    dir: cmd/srs-milter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - darwin
archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: SaaS Web Internet Solutions GmbH
    homepage: https://github.com/d--j/srs-milter
    maintainer: Daniel Jagszent <daniel.jagszent@saasweb.net>
    description: |-
      Mail filter handling SRS address rewriting
      A Postfix and Sendmail compatible milter that does SRS address rewriting.
    license: BSD 2-Clause
    section: mail
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: packaging/srs-milter.service
        dst: /lib/systemd/system/srs-milter.service
      - dst: /etc/srs-milter
        type: dir
        packager: rpm
        file_info:
          mode: 0750
          owner: root
          group: nobody
      - dst: /etc/srs-milter
        type: dir
        packager: deb
        file_info:
          mode: 0750
          owner: root
          group: nogroup
      - dst: /etc/srs-milter
        type: dir
        packager: apk
        file_info:
          mode: 0750
          owner: root
          group: nogroup
      - src: packaging/srs-milter.yml
        dst: /etc/srs-milter/srs-milter.yml
        type: "config|noreplace"
        packager: rpm
        file_info:
          mode: 0640
          owner: root
          group: nobody
      - src: packaging/srs-milter.yml
        dst: /etc/srs-milter/srs-milter.yml
        type: "config|noreplace"
        packager: deb
        file_info:
          mode: 0640
          owner: root
          group: nobody
      - src: packaging/srs-milter.yml
        dst: /etc/srs-milter/srs-milter.yml
        type: "config|noreplace"
        packager: apk
        file_info:
          mode: 0640
          owner: root
          group: nobody
      - src: packaging/srs-milter.1.gz
        dst: /usr/share/man/man1/
      - src: ./packaging/copyright
        dst: /usr/share/doc/srs-milter/copyright
        packager: deb
    scripts:
      postinstall: "packaging/postinstall.sh"
    deb:
      triggers:
        activate_noawait:
          - mandb
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
        - maintainer-script-calls-systemctl
        - non-standard-dir-perm
        - non-standard-file-perm
        - binary-without-manpage
