= srs-milter(1)
Daniel Jagszent
v0.0.0
:doctype: manpage
:man manual: srs-milter Manual
:man source: srs-milter {revnumber}

== Name

srs-milter - Mail filter handling SRS address rewriting

== Synopsis

*srs-milter* [_OPTION_]...

== Description

The srs-milter(1) daemon is a Postfix and Sendmail compatible milter that does SRS address rewriting.

== Options

// tag::options[]
*-help*::
  Print a help message.

*-addr* _string_::
  Bind to address/port or unix domain socket path (default "127.0.0.1:10382")

*-proto* _string_::
  Protocol family (unix or tcp) (default "tcp")

*-forward* _email_::
  email to do forward SRS lookup for. If specified the milter will not be started.

*-reverse* _email_::
  email to do reverse SRS lookup for. If specified the milter will not be started.

*-systemd*::
  enable systemd mode (log without date/time)
// end::options[]

== Exit Status

*0*::
  Success.

*1*::
  Failure (usage error; configuration error; unexpected error).

== Bugs

Refer to the *srs-milter* issue tracker at https://github.com/d--j/srs-milter/issues?q=is%3Aopen.

== Copying

Copyright \(C) 2023-present Daniel Jagszent.
Use of this software is granted under the terms of the BSD 2-Clause License.
